# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1213, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_analysis = QtWidgets.QLabel(self.centralwidget)
        self.img_analysis.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.img_analysis.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img_analysis.setAlignment(QtCore.Qt.AlignCenter)
        self.img_analysis.setObjectName("img_analysis")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 640, 641, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_gene_data = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_gene_data.setObjectName("btn_gene_data")
        self.horizontalLayout.addWidget(self.btn_gene_data)
        self.btn_cls = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_cls.setObjectName("btn_cls")
        self.horizontalLayout.addWidget(self.btn_cls)
        self.btn_sche = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_sche.setObjectName("btn_sche")
        self.horizontalLayout.addWidget(self.btn_sche)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 500, 641, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.input_box_11 = QtWidgets.QHBoxLayout()
        self.input_box_11.setContentsMargins(5, 5, 5, 5)
        self.input_box_11.setObjectName("input_box_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_11.setObjectName("label_11")
        self.input_box_11.addWidget(self.label_11)
        self.mcls = QtWidgets.QLineEdit(self.layoutWidget1)
        self.mcls.setObjectName("mcls")
        self.input_box_11.addWidget(self.mcls)
        self.input_box_11.setStretch(0, 1)
        self.input_box_11.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_11, 1, 3, 1, 1)
        self.input_box_9 = QtWidgets.QHBoxLayout()
        self.input_box_9.setContentsMargins(5, 5, 5, 5)
        self.input_box_9.setObjectName("input_box_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_9.setObjectName("label_9")
        self.input_box_9.addWidget(self.label_9)
        self.pnum = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pnum.setObjectName("pnum")
        self.input_box_9.addWidget(self.pnum)
        self.input_box_9.setStretch(0, 1)
        self.input_box_9.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_9, 1, 1, 1, 1)
        self.input_box_6 = QtWidgets.QHBoxLayout()
        self.input_box_6.setContentsMargins(5, 5, 5, 5)
        self.input_box_6.setObjectName("input_box_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_6.setObjectName("label_6")
        self.input_box_6.addWidget(self.label_6)
        self.Np = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Np.setObjectName("Np")
        self.input_box_6.addWidget(self.Np)
        self.input_box_6.setStretch(0, 1)
        self.input_box_6.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_6, 2, 2, 1, 1)
        self.input_box_7 = QtWidgets.QHBoxLayout()
        self.input_box_7.setContentsMargins(5, 5, 5, 5)
        self.input_box_7.setObjectName("input_box_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_7.setObjectName("label_7")
        self.input_box_7.addWidget(self.label_7)
        self.Gm = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Gm.setObjectName("Gm")
        self.input_box_7.addWidget(self.Gm)
        self.input_box_7.setStretch(0, 1)
        self.input_box_7.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_7, 2, 3, 1, 1)
        self.input_box_12 = QtWidgets.QHBoxLayout()
        self.input_box_12.setContentsMargins(5, 5, 5, 5)
        self.input_box_12.setObjectName("input_box_12")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_12.setObjectName("label_12")
        self.input_box_12.addWidget(self.label_12)
        self.seed = QtWidgets.QLineEdit(self.layoutWidget1)
        self.seed.setObjectName("seed")
        self.input_box_12.addWidget(self.seed)
        self.input_box_12.setStretch(0, 1)
        self.input_box_12.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_12, 1, 0, 1, 1)
        self.input_box_5 = QtWidgets.QHBoxLayout()
        self.input_box_5.setContentsMargins(5, 5, 5, 5)
        self.input_box_5.setObjectName("input_box_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_5.setObjectName("label_5")
        self.input_box_5.addWidget(self.label_5)
        self.CR = QtWidgets.QLineEdit(self.layoutWidget1)
        self.CR.setObjectName("CR")
        self.input_box_5.addWidget(self.CR)
        self.input_box_5.setStretch(0, 1)
        self.input_box_5.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_5, 2, 1, 1, 1)
        self.input_box_2 = QtWidgets.QHBoxLayout()
        self.input_box_2.setContentsMargins(5, 5, 5, 5)
        self.input_box_2.setObjectName("input_box_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_2.setObjectName("label_2")
        self.input_box_2.addWidget(self.label_2)
        self.cell_size = QtWidgets.QLineEdit(self.layoutWidget1)
        self.cell_size.setObjectName("cell_size")
        self.input_box_2.addWidget(self.cell_size)
        self.input_box_2.setStretch(0, 1)
        self.input_box_2.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_2, 2, 0, 1, 1)
        self.input_box_8 = QtWidgets.QHBoxLayout()
        self.input_box_8.setContentsMargins(5, 5, 5, 5)
        self.input_box_8.setObjectName("input_box_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_8.setObjectName("label_8")
        self.input_box_8.addWidget(self.label_8)
        self.strategy = QtWidgets.QLineEdit(self.layoutWidget1)
        self.strategy.setObjectName("strategy")
        self.input_box_8.addWidget(self.strategy)
        self.input_box_8.setStretch(0, 1)
        self.input_box_8.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_8, 3, 3, 1, 1)
        self.input_box_10 = QtWidgets.QHBoxLayout()
        self.input_box_10.setContentsMargins(5, 5, 5, 5)
        self.input_box_10.setObjectName("input_box_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_10.setObjectName("label_10")
        self.input_box_10.addWidget(self.label_10)
        self.mnum = QtWidgets.QLineEdit(self.layoutWidget1)
        self.mnum.setObjectName("mnum")
        self.input_box_10.addWidget(self.mnum)
        self.input_box_10.setStretch(0, 1)
        self.input_box_10.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_10, 1, 2, 1, 1)
        self.input_box = QtWidgets.QHBoxLayout()
        self.input_box.setContentsMargins(5, 5, 5, 5)
        self.input_box.setObjectName("input_box")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label.setObjectName("label")
        self.input_box.addWidget(self.label)
        self.rt = QtWidgets.QLineEdit(self.layoutWidget1)
        self.rt.setObjectName("rt")
        self.input_box.addWidget(self.rt)
        self.input_box.setStretch(0, 1)
        self.input_box.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box, 3, 0, 1, 1)
        self.input_box_3 = QtWidgets.QHBoxLayout()
        self.input_box_3.setContentsMargins(5, 5, 5, 5)
        self.input_box_3.setObjectName("input_box_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_3.setObjectName("label_3")
        self.input_box_3.addWidget(self.label_3)
        self.cancel_order = QtWidgets.QLineEdit(self.layoutWidget1)
        self.cancel_order.setObjectName("cancel_order")
        self.input_box_3.addWidget(self.cancel_order)
        self.input_box_3.setStretch(0, 1)
        self.input_box_3.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_3, 3, 1, 1, 1)
        self.input_box_4 = QtWidgets.QHBoxLayout()
        self.input_box_4.setContentsMargins(5, 5, 5, 5)
        self.input_box_4.setObjectName("input_box_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_4.setObjectName("label_4")
        self.input_box_4.addWidget(self.label_4)
        self.weights = QtWidgets.QLineEdit(self.layoutWidget1)
        self.weights.setObjectName("weights")
        self.input_box_4.addWidget(self.weights)
        self.input_box_4.setStretch(0, 1)
        self.input_box_4.setStretch(1, 1)
        self.gridLayout.addLayout(self.input_box_4, 3, 2, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 1)
        self.gridLayout.setColumnMinimumWidth(1, 1)
        self.gridLayout.setColumnMinimumWidth(2, 1)
        self.gridLayout.setColumnMinimumWidth(3, 1)
        self.gridLayout.setRowMinimumHeight(0, 1)
        self.gridLayout.setRowMinimumHeight(1, 1)
        self.gridLayout.setRowMinimumHeight(2, 1)
        self.gridLayout.setRowMinimumHeight(3, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.display = QtWidgets.QTextBrowser(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(660, 10, 541, 661))
        self.display.setObjectName("display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1213, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.img_analysis.setText(_translate("MainWindow", "Analysis"))
        self.btn_gene_data.setText(_translate("MainWindow", "生成数据"))
        self.btn_cls.setText(_translate("MainWindow", "训练分类器"))
        self.btn_sche.setText(_translate("MainWindow", "开始调度"))
        self.label_11.setText(_translate("MainWindow", "机器种类"))
        self.label_9.setText(_translate("MainWindow", "工件数量"))
        self.label_6.setText(_translate("MainWindow", "种群大小"))
        self.label_7.setText(_translate("MainWindow", "最大代数"))
        self.label_12.setText(_translate("MainWindow", "随机种子"))
        self.label_5.setText(_translate("MainWindow", "变异率"))
        self.label_2.setText(_translate("MainWindow", "单元大小"))
        self.label_8.setText(_translate("MainWindow", "选择策略"))
        self.label_10.setText(_translate("MainWindow", "机器数量"))
        self.label.setText(_translate("MainWindow", "重调度T"))
        self.label_3.setText(_translate("MainWindow", "取消订单"))
        self.label_4.setText(_translate("MainWindow", "权重"))

